// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAZ29D6wc1jzPlbfJ_8mKHxp6-xuV6hLNQ',
    appId: '1:1084592092620:android:c0c13f80260e4ffd685969',
    messagingSenderId: '1084592092620',
    projectId: 'test-8502d',
    databaseURL: 'https://test-8502d.firebaseio.com',
    storageBucket: 'test-8502d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB5atylFgHLiD4eADRsOItwn5vu8VfX1Iw',
    appId: '1:1084592092620:ios:bf6940f9cad56750685969',
    messagingSenderId: '1084592092620',
    projectId: 'test-8502d',
    databaseURL: 'https://test-8502d.firebaseio.com',
    storageBucket: 'test-8502d.appspot.com',
    androidClientId: '1084592092620-0dsij7c0v53cepo5t6bil5sca877h008.apps.googleusercontent.com',
    iosClientId: '1084592092620-64el4n29doi3tred4eold1ndd8b0d9kn.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterFireTest',
  );
}
